apiVersion: v1
kind: Service
metadata:
  name: azure-code-lb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: redis
  selector:
    app: "{{ .Values.name }}"

